name: trader

on:
  # Temporarily disabled to unblock trunk
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: trader

jobs:
  test:
    name: test trader
    runs-on: ubuntu-latest
    env:
      GOVER: 1.17
    services:
      spiced:
        image: ghcr.io/spiceai/spiced:latest
        ports:
        - 8000:8000
        options: |
          -v ${{ github.workspace }}/trader:/app
    steps:
      - uses: actions/checkout@v2

      - name: update PATH
        run: |
          echo "PATH=~/.spice/bin:$PATH" >> $GITHUB_ENV

      - name: install Spice.ai
        run: |
          curl https://install.spiceai.org | /bin/bash

      - name: check Spice.ai runtime
        run: |
          curl http://localhost:8000/health

      - name: get quickstart pod
        run: |
          spice add quickstarts/trader

      - name: install npm packages
        run: |
          npm install

      - name: start training
        run: |
          spice train trader

      - name: start Trader app
        run: |
          node main.js

      - name: Fetch recommendations
        run: |
          curl http://localhost:8000/api/v0.1/pods/trader/recommendation

      - name: Fetch observations
        run: |
          curl http://localhost:8000/api/v0.1/pods/trader/observations

      - name: stop Trader app
        run: |
          killall node
